// MultiMichel content graph — single source of truth for indexes & archive.
// Provenance: research/sources.json. verification: primary | secondary | user | review
// date       — ISO, the ONLY value anything sorts on (YYYY | YYYY-MM | YYYY-MM-DD)
// displayDate— human string, the ONLY value anything renders
// publicArchive:false — a real record, kept as evidence, not shown in the
//              public archive. "All" in the archive means all PUBLIC entries.
window.MM = {
person: {name:"Michel Ferreira", aka:"MultiMichel", location:"Sydney, Australia", role:"Designer Advocate at Figma", since:1998, contact:"michel@multimichel.com"},
// The route is a fast career scan, not a full CV. It stops at Album Agency —
// everything before 1998–2007 lives on LinkedIn and is linked, never restated
// here as a synthetic catch-all row.
experience: [
{company:"Figma", role:"Designer Advocate", start:"Sep 2025", end:"present", city:"Sydney", verification:"user"},
{company:"Xero", role:"Lead Product Designer", start:"Mar 2025", end:"Sep 2025", city:"Sydney", verification:"user"},
{company:"Atlassian", role:"Senior Product Designer — Design Manager", start:"Jun 2019", end:"Jan 2025", city:"Sydney", verification:"user"},
{company:"Shopify", role:"Senior Product Designer", start:"May 2017", end:"Apr 2019", city:"Canada", verification:"user"},
{company:"Booking.com", role:"Designer", start:"Jun 2013", end:"May 2017", city:"Amsterdam", verification:"user"},
{company:"Album Agency", role:"Design Director", start:"Feb 2007", end:"May 2013", city:"California", verification:"user"}
],
items: [
{id:"work-atlassian", type:"Work", year:2024, date:"2024", title:"Jira Nav to Atlassian's System of Work", sub:"How a 2% satisfaction rate became the foundation for Atlassian's future", href:"work-atlassian.html", company:"Atlassian", verification:"primary"},
{id:"work-booking", type:"Work", year:2016, date:"2016", title:"Helping Booking.com's Help Center", sub:"Self-service that cut support tickets 30% and saved $1M+ in three months", href:"work-booking.html", company:"Booking.com", verification:"primary"},
{id:"w-fast-good", type:"Writing", year:2026, date:"2026-06", displayDate:"Jun 2026", title:"Fast ≠ Good", sub:"Everyone wants us to deliver more faster. How does design defend building for good in the age of fast?", url:"https://multimichel.medium.com/fast-good-80a9af2f0fb8", platform:"Medium", featured:true, verification:"primary"},
{id:"w-dialects", type:"Writing", year:2025, date:"2025-10-16", displayDate:"Oct 16, 2025", title:"Design Dialects: Breaking the Rules, Not the System", sub:"Design systems aren't component libraries — they're living languages. Fluent systems bend without breaking.", url:"https://alistapart.com/article/design-dialects-breaking-the-rules-not-the-system/", publication:"A List Apart", featured:true, verification:"primary"},
{id:"w-holistic", type:"Writing", year:2025, date:"2025-07-23", displayDate:"Jul 23, 2025", title:"An Holistic Framework for Shared Design Leadership", sub:"Design Manager and Lead Designer on one team isn't about dividing territories. It's about multiplying impact.", url:"https://alistapart.com/article/an-holistic-framework-for-shared-design-leadership/", publication:"A List Apart", featured:true, verification:"primary"},
{id:"w-death-of", type:"Writing", year:2025, date:"2025-03-29", displayDate:"Mar 29, 2025", title:"The Death of \u201CThe Death Of\u201D Posts", sub:"Why we keep staging funerals for ideas that are still very much alive.", url:"https://multimichel.medium.com/the-death-of-the-death-of-posts-c1ed95fb4526", platform:"Medium", verification:"primary"},
{id:"w-title", type:"Writing", year:2025, date:"2025-03-13", displayDate:"Mar 13, 2025", title:"Title is (still) not important", sub:"The eternal existential conundrum.", url:"https://multimichel.medium.com/title-is-still-not-important-b36f91b25dac", platform:"Medium", verification:"primary"},
{id:"w-future-tech", type:"Writing", year:2023, date:"2023-04-12", displayDate:"Apr 12, 2023", title:"Tech of the Future and the Future of Tech", sub:"Steering towards a sustainable and ethical industry.", url:"https://multimichel.medium.com/tech-of-the-future-and-the-future-of-tech-ea95b158eedf", platform:"Medium", verification:"primary"},
{id:"w-shipping", type:"Writing", year:2023, date:"2023-03-25", displayDate:"Mar 25, 2023", title:"\u201CShipping in the next 2 weeks\u201D is tech's version of \u201CI just need to lose 5 pounds\u201D", url:"https://multimichel.medium.com/shipping-in-the-next-2-weeks-is-techs-version-of-i-just-need-to-loose-5-pounds-d17caba49cc", platform:"Medium", verification:"primary"},
{id:"w-magic", type:"Writing", year:2023, date:"2023-02-23", displayDate:"Feb 23, 2023", title:"Seeing magic in everyday things", url:"https://multimichel.medium.com/seeing-magic-in-everyday-things-7c7846522301", platform:"Medium", verification:"primary"},
{id:"w-10-lessons", type:"Writing", year:2021, date:"2021-04-30", displayDate:"Apr 30, 2021", title:"10 lessons learned from recording my first 10 podcast episodes of Latinxs Who Design", url:"https://multimichel.medium.com/10-lessons-learned-from-recording-my-first-10-podcast-episodes-of-latinxs-who-design-914861dd4184", platform:"Medium", verification:"primary"},
{id:"w-toolbelt", type:"Writing", year:2021, date:"2021-01-22", displayDate:"Jan 22, 2021", title:"What are the essential tools on a Designer's Toolbelt?", url:"https://multimichel.medium.com/what-are-the-essential-tools-on-a-designers-toolbelt-d765b1abd4ca", publication:"Designer's Toolbelt", platform:"Medium", verification:"primary"},
{id:"w-fries", type:"Writing", year:2015, date:"2015-09-21", displayDate:"Sep 21, 2015", title:"Would you like fries with that?", sub:"Discussing the hamburger icon.", url:"https://multimichel.medium.com/would-you-like-fries-with-that-4edf46849380", publication:"Booking.com Design", platform:"Medium", verification:"primary"},
{id:"w-rwd", type:"Writing", year:2014, date:"2014-10-22", displayDate:"Oct 22, 2014", title:"RWD or Apps? YES!", sub:"Does responsive design negate the need for an app?", url:"https://multimichel.medium.com/803053bfcec3", platform:"Medium", verification:"primary"},
{id:"w-nba-bubble", type:"Writing", year:2020, date:"2020-10-02", displayDate:"Oct 2, 2020", title:"11 Lessons from the NBA Bubble for Your Newly Remote Team", sub:"What the NBA's pandemic bubble can teach remote teams about collaboration and performance.", url:"https://www.atlassian.com/blog/teamwork/11-lessons-from-the-nba-bubble-for-your-newly-remote-team", publication:"Atlassian Blog", verification:"primary"},
// ---------- SPEAKING ----------
// Grammar: talkTitle when known -> title line, event brand + location + date
// as metadata. No talkTitle -> the event brand IS the title. Location is only
// repeated when it is not already carried by the event's own branding.
// The same talk delivered at two events is TWO records, never merged. A record
// with no url still renders — it simply carries no arrow.
{id:"t-design-matters", type:"Talk", year:2026, date:"2026-11", displayDate:"Nov 2026", talkTitle:null, eventName:"Design Matters 26", location:"Tokyo", showLocation:true, featured:true, status:"upcoming", format:"talk", role:"speaker", url:"https://dm26.spectrumtokyo.com/speakers/michel/", verification:"user"},
{id:"t-maker-collective", type:"Talk", year:2026, date:"2026-08", displayDate:"Aug 2026", talkTitle:null, eventName:"Maker Collective", location:"Sydney", showLocation:true, featured:true, status:"past", format:"talk", role:"speaker", verification:"user"},
{id:"t-fof-perth", type:"Talk", year:2026, date:"2026-07", displayDate:"Jul 2026", talkTitle:null, eventName:"Friends of Figma Perth", location:"Perth", showLocation:true, status:"past", format:"talk", role:"speaker", organization:"Figma", verification:"user"},
{id:"t-config", type:"Talk", year:2026, date:"2026-06", displayDate:"Jun 2026", talkTitle:"Figma learning lab: workflow tips \u2014 from slow to flow", eventName:"Config 2026", location:"San Francisco", showLocation:true, status:"past", format:"talk", role:"speaker", sub:"With Chad Bergman.", organization:"Figma", url:"https://config.figma.com/san-francisco/speakers/", verification:"primary"},
{id:"t-aixdesign", type:"Talk", year:2026, date:"2026-06", displayDate:"Jun 2026", talkTitle:"Fast \u2260 Good", eventName:"AI \u00D7 Design", location:"Melbourne", showLocation:true, featured:true, status:"past", format:"talk", role:"speaker", url:"https://conffab.com/presentation/fast-\u2260-good/?gl=5ulxY9lWmOlu", videoUrl:"https://conffab.com/presentation/fast-\u2260-good/?gl=5ulxY9lWmOlu", verification:"user"},
{id:"t-figma-down-under", type:"Talk", year:2026, date:"2026-04", displayDate:"Apr 2026", talkTitle:null, eventName:"Figma Down Under", location:"Melbourne", showLocation:true, status:"past", format:"talk", role:"speaker", organization:"Figma", verification:"user"},
{id:"t-ccx-sydney", type:"Talk", year:2026, date:"2026-04", displayDate:"Apr 2026", talkTitle:"I think your design system is broken", eventName:"CCX Sydney", location:"Sydney", showLocation:false, status:"past", format:"talk", role:"speaker", note:"Same talk as t-uxcamp, a later delivery. Archive-only by choice \u2014 Home features the UXCamp version.", verification:"user"},
{id:"t-cm-sydney", type:"Talk", year:2026, date:"2026-03", displayDate:"Mar 2026", talkTitle:"Gambiarra", eventName:"CreativeMornings Sydney", location:"Sydney", showLocation:false, featured:true, status:"past", format:"talk", role:"speaker", verification:"user"},
{id:"t-melbourne-service-jam", type:"Talk", year:2026, date:"2026-03", displayDate:"Mar 2026", talkTitle:null, eventName:"Melbourne Service Jam", location:"Melbourne", showLocation:true, status:"past", format:"workshop", role:"mentor", verification:"user"},
{id:"t-design-systems-figma-sydney", type:"Talk", year:2026, date:"2026-03", displayDate:"Mar 2026", talkTitle:null, eventName:"Design Systems with Figma: Sydney", location:"Sydney", showLocation:false, status:"past", format:"talk", role:"speaker", organization:"Figma", verification:"user"},
{id:"t-echos-cis", type:"Talk", year:2026, date:"2026", displayDate:"2026", talkTitle:null, eventName:"Echos Creative Intelligence Summit", location:null, showLocation:false, status:"past", format:"panel", role:"panelist", organization:"Echos", verification:"user"},
{id:"t-figma-askable", type:"Talk", year:2026, date:"2026-02", displayDate:"Feb 2026", talkTitle:"Insight to prototype in minutes using Askable AI & Figma Make", eventName:"Figma \u00D7 Askable", location:null, showLocation:false, status:"past", format:"talk", role:"speaker", organization:"Figma", note:"Format unconfirmed (session vs webinar).", verification:"user"},
{id:"t-psn-trust", type:"Talk", year:2026, date:"2026-05", displayDate:"May 2026", talkTitle:"Design Services Citizens Can Trust", eventName:"Public Sector Network", location:null, showLocation:false, status:"past", format:"talk", role:"speaker", note:"Format unconfirmed (talk vs panel).", verification:"user"},
{id:"t-figma-day-config", type:"Talk", year:2026, date:"2026-08", displayDate:"Aug 2026", talkTitle:"Novidades da Config 2026", eventName:"Figma Day", location:null, showLocation:false, status:"past", format:"talk", role:"speaker", organization:"Figma", lang:"pt-BR", verification:"user"},
{id:"t-uxcamp", type:"Talk", year:2025, date:"2025-11", displayDate:"Nov 2025", talkTitle:"I think your design system is broken", eventName:"UXCamp Naarm | Melbourne 2025", location:"Melbourne", showLocation:false, featured:true, status:"past", format:"talk", role:"speaker", url:"https://youtu.be/vvY0Lh-7Hn0?si=L7V4Z_0b5_p02tBb", videoUrl:"https://youtu.be/vvY0Lh-7Hn0?si=L7V4Z_0b5_p02tBb", note:"Featured on Home over the CCX Sydney delivery of the same talk: stronger public artifact, including the recording. Both records stand \u2014 never deduped.", verification:"user"},
{id:"t-design-systems-next-era", type:"Talk", year:2025, date:"2025-11", displayDate:"Nov 2025", talkTitle:null, eventName:"Design Systems for the Next Era", location:"Sydney", showLocation:true, status:"past", format:"keynote", role:"co-presenter", organization:"Figma", verification:"user"},
{id:"t-echos-2024", type:"Talk", year:2024, date:"2024", displayDate:"2024", talkTitle:"The New Design Leadership Paradigm: Career & Leadership", eventName:"Echos Design Leadership", location:null, showLocation:false, status:"past", format:"talk", role:"speaker", organization:"Echos", verification:"user"},
{id:"t-echos-2023", type:"Talk", year:2023, date:"2023-05", displayDate:"May 2023", talkTitle:"Shaping Design Culture with Design Systems", eventName:"Echos Design Leadership", location:null, showLocation:false, status:"past", format:"talk", role:"speaker", organization:"Echos", verification:"user"},
{id:"t-adplist-2023", type:"Talk", year:2023, date:"2023", displayDate:"2023", talkTitle:"Future-proofing Your Design Career", eventName:"ADPList World Tour Sydney", location:"Sydney", showLocation:false, status:"past", format:"talk", role:"speaker", verification:"user"},
{id:"t-echos-2022-jun", type:"Talk", year:2022, date:"2022-06", displayDate:"Jun 2022", talkTitle:"Creating High Value Products", eventName:"Echos Design Leadership", location:null, showLocation:false, featured:true, status:"past", format:"workshop", role:"workshop-leader", organization:"Echos", url:"https://echos.cc/design-leadership/", verification:"user"},
{id:"t-echos-2022-sep", type:"Talk", year:2022, date:"2022-09", displayDate:"Sep 2022", talkTitle:"The Journey of Design Leadership", eventName:"Echos Design Leadership", location:null, showLocation:false, status:"past", format:"talk", role:"speaker", organization:"Echos", verification:"user"},
{id:"t-echos-2022-rep", type:"Talk", year:2022, date:"2022", displayDate:"2022", talkTitle:"Design Leadership and Representation", eventName:"Echos Design Leadership", location:null, showLocation:false, status:"past", format:"talk", role:"speaker", organization:"Echos", verification:"user"},
{id:"t-echos-2021", type:"Talk", year:2021, date:"2021-09", displayDate:"Sep 2021", talkTitle:"Building a Design Language as Design Ops", eventName:"Echos Design Leadership", location:null, showLocation:false, status:"past", format:"workshop", role:"workshop-leader", organization:"Echos", verification:"user"},
{id:"t-ila21", type:"Talk", year:2021, date:"2021", displayDate:"2021", talkTitle:"Dise\u00F1o a viva voz / Design Out Loud", eventName:"Interaction Latin America 2021 / ILA21", location:null, showLocation:false, status:"past", format:"panel", role:"panelist", url:"https://ila21.ixda.org/en/speakers.html", verification:"secondary"},
{id:"t-outlook", type:"Talk", year:2026, date:"2026-04", displayDate:"Apr 2026", talkTitle:"Product Deep-Dive: Figma", eventName:"The Outlook (TO26)", location:"Australia", showLocation:true, status:"past", format:"talk", role:"speaker", organization:"Figma", url:"https://wearetheoutlook.com.au/program", publicArchive:false, note:"Listed on the TO26 programme but Michel did not attend or present \u2014 not a speaking appearance. Kept as evidence only so the programme listing is not mistaken for a talk later.", verification:"secondary"},
{id:"t-philips-digisummit", type:"Talk", year:2017, date:"2017-03", displayDate:"Mar 2017", talkTitle:null, eventName:"Philips DigiSummit", location:null, showLocation:false, status:"past", format:"talk", role:"speaker", note:"Confirmed by surviving attendee posts showing Michel presenting Booking.com's experimentation approach. No formal talk title established \u2014 do not invent one.", verification:"secondary"},
{id:"t-sogd-generate", type:"Talk", year:2016, date:"2016", displayDate:"2016", talkTitle:"The Science of Good Design", eventName:"Generate London", location:"London", showLocation:false, featured:true, status:"past", format:"talk", role:"speaker", url:"https://www.youtube.com/watch?v=4Nk0ray32i0", videoUrl:"https://www.youtube.com/watch?v=4Nk0ray32i0", verification:"primary"},
{id:"t-sogd-codetalks", type:"Talk", year:2016, date:"2016", displayDate:"2016", talkTitle:"The Science of Good Design", eventName:"CODETALKS.DE", location:"Hamburg, Germany", showLocation:true, status:"past", format:"talk", role:"speaker", related:["t-sogd-generate"], note:"Separate delivery from Generate London \u2014 two events, two records. No surviving URL for this one.", verification:"secondary"},
{id:"t-ddsot-fedc", type:"Talk", year:2016, date:"2016-06", displayDate:"Jun 2016", talkTitle:"Data and Design Sitting on a Tree", eventName:"Front-End Design Conference", location:"St. Petersburg, Florida", showLocation:true, status:"past", format:"workshop", role:"workshop-leader", sub:"With Andy Warburton.", note:"Title is the presentation title, not the format \u2014 do not render as \"A/B Testing Workshop\".", verification:"user"},
{id:"t-ddsot-amsterdam", type:"Talk", year:2016, date:"2016-07", displayDate:"Jul 2016", talkTitle:"Data and Design Sitting on a Tree", eventName:"Hack the Future Refugee Meetup", location:"Amsterdam", showLocation:true, status:"past", format:"workshop", role:"workshop-leader", related:["t-ddsot-fedc"], note:"Second delivery of the same workshop \u2014 a separate event, never collapsed with the Front-End Design Conference record.", verification:"user"},
{id:"t-convergese", type:"Talk", year:2015, date:"2015-04", displayDate:"Apr 2015", talkTitle:"Data, Designers and Decisions", eventName:"ConvergeSE", location:"Columbia, South Carolina", showLocation:true, featured:true, status:"past", format:"talk", role:"speaker", sub:"Edward Riordan participated in part of the session.", note:"Michel's contemporaneous post says \"Data, decisions and designers\"; his resume says \"Data, Designers and Decisions\". The resume wording is canonical.", verification:"user"},
{id:"t-ga-atlanta", type:"Talk", year:2015, date:"2015-04", displayDate:"Apr 2015", talkTitle:"Designing with Data", eventName:"General Assembly Atlanta \u00D7 IxDA Atlanta", location:"Atlanta", showLocation:true, status:"past", format:"talk", role:"speaker", verification:"user"},
// Latinxs Who Design — episodes Michel created and hosted. Verified against
// the Apple Podcasts catalogue (itunes lookup, collection 1554011225):
// titles, guests, publication dates and URLs are as published, not
// reconstructed. An external show that INTERVIEWS Michel is type Interview,
// not Podcast — the type records his role, not the medium.
{id:"lwd-jay-demetillo", type:"Podcast", year:2023, date:"2023-04-28", displayDate:"Apr 28, 2023", title:"Embracing Design Inclusion & Social Impact: A Conversation with Jay Demetillo", guest:"Jay Demetillo", publication:"Latinxs Who Design", url:"https://podcasts.apple.com/us/podcast/embracing-design-inclusion-social-impact-a/id1554011225?i=1000610964244&uo=4", verification:"primary"},
{id:"lwd-diego-pulido-and-koji-pereira", type:"Podcast", year:2022, date:"2022-09-14", displayDate:"Sep 14, 2022", title:"Journey to Design Leadership with Diego Pulido and Koji Pereira", guest:"Diego Pulido and Koji Pereira", publication:"Latinxs Who Design", url:"https://podcasts.apple.com/us/podcast/journey-to-design-leadership-with-diego-pulido-and/id1554011225?i=1000579460055&uo=4", verification:"primary"},
{id:"lwd-kevin-bethune", type:"Podcast", year:2022, date:"2022-04-14", displayDate:"Apr 14, 2022", title:"Reimagining Design with Kevin Bethune", guest:"Kevin Bethune", publication:"Latinxs Who Design", url:"https://podcasts.apple.com/us/podcast/reimagining-design-with-kevin-bethune/id1554011225?i=1000557562031&uo=4", verification:"primary"},
{id:"lwd-aubrey-blanche", type:"Podcast", year:2022, date:"2022-03-22", displayDate:"Mar 22, 2022", title:"Introducing By us not biased: Episode 1: Aubrey Blanche talks Equitable Design", guest:"Aubrey Blanche", publication:"Latinxs Who Design", url:"https://podcasts.apple.com/us/podcast/introducing-by-us-not-biased-episode-1-aubrey-blanche/id1554011225?i=1000554796611&uo=4", verification:"primary"},
{id:"lwd-joanna-pe-a-bickley", type:"Podcast", year:2021, date:"2021-10-25", displayDate:"Oct 25, 2021", title:"Be Bold - Joanna Peña-Bickley", guest:"Joanna Peña-Bickley", publication:"Latinxs Who Design", url:"https://podcasts.apple.com/us/podcast/be-bold-joanna-pe%C3%B1a-bickley/id1554011225?i=1000539581936&uo=4", verification:"primary"},
{id:"lwd-andrei-herasimchuk", type:"Podcast", year:2021, date:"2021-09-29", displayDate:"Sep 29, 2021", title:"Leverage your community - Andrei Herasimchuk", guest:"Andrei Herasimchuk", publication:"Latinxs Who Design", url:"https://podcasts.apple.com/us/podcast/leverage-your-community-andrei-herasimchuk/id1554011225?i=1000536995906&uo=4", verification:"primary"},
{id:"lwd-diego-pulido", type:"Podcast", year:2021, date:"2021-09-14", displayDate:"Sep 14, 2021", title:"Persistence pays off - Diego Pulido", guest:"Diego Pulido", publication:"Latinxs Who Design", url:"https://podcasts.apple.com/us/podcast/persistence-pays-off-diego-pulido/id1554011225?i=1000535250957&uo=4", verification:"primary"},
{id:"lwd-rachel-smith", type:"Podcast", year:2021, date:"2021-08-31", displayDate:"Aug 31, 2021", title:"Never compare yourself - Rachel Smith", guest:"Rachel Smith", publication:"Latinxs Who Design", url:"https://podcasts.apple.com/us/podcast/never-compare-yourself-rachel-smith/id1554011225?i=1000533829057&uo=4", verification:"primary"},
{id:"lwd-yvonne-blanco", type:"Podcast", year:2021, date:"2021-08-24", displayDate:"Aug 24, 2021", title:"Don't limit yourself - Yvonne Blanco", guest:"Yvonne Blanco", publication:"Latinxs Who Design", url:"https://podcasts.apple.com/us/podcast/dont-limit-yourself-yvonne-blanco/id1554011225?i=1000532945136&uo=4", verification:"primary"},
{id:"lwd-miguel-miggi-angel-cardona", type:"Podcast", year:2021, date:"2021-08-10", displayDate:"Aug 10, 2021", title:"You're rewarded for risks you take - Miguel (Miggi) Angel Cardona", guest:"Miguel (Miggi) Angel Cardona", publication:"Latinxs Who Design", url:"https://podcasts.apple.com/us/podcast/youre-rewarded-for-risks-you-take-miguel-miggi-angel/id1554011225?i=1000531576242&uo=4", verification:"primary"},
{id:"lwd-pj-pereira", type:"Podcast", year:2021, date:"2021-08-03", displayDate:"Aug 3, 2021", title:"The value of being an outsider - PJ Pereira", guest:"PJ Pereira", publication:"Latinxs Who Design", url:"https://podcasts.apple.com/us/podcast/the-value-of-being-an-outsider-pj-pereira/id1554011225?i=1000530838481&uo=4", verification:"primary"},
{id:"lwd-mariel-backman", type:"Podcast", year:2021, date:"2021-06-08", displayDate:"Jun 8, 2021", title:"Educate yourself - Mariel Backman", guest:"Mariel Backman", publication:"Latinxs Who Design", url:"https://podcasts.apple.com/us/podcast/educate-yourself-mariel-backman/id1554011225?i=1000524588003&uo=4", verification:"primary"},
{id:"lwd-cami-nunes", type:"Podcast", year:2021, date:"2021-06-01", displayDate:"Jun 1, 2021", title:"Put yourself out there - Cami Nunes", guest:"Cami Nunes", publication:"Latinxs Who Design", url:"https://podcasts.apple.com/us/podcast/put-yourself-out-there-cami-nunes/id1554011225?i=1000523725562&uo=4", verification:"primary"},
{id:"lwd-daniela-jorge", type:"Podcast", year:2021, date:"2021-05-25", displayDate:"May 25, 2021", title:"We’re wired to be humble - Daniela Jorge", guest:"Daniela Jorge", publication:"Latinxs Who Design", url:"https://podcasts.apple.com/us/podcast/were-wired-to-be-humble-daniela-jorge/id1554011225?i=1000522980327&uo=4", verification:"primary"},
{id:"lwd-fabio-sasso", type:"Podcast", year:2021, date:"2021-05-18", displayDate:"May 18, 2021", title:"Best investment is in yourself - Fabio Sasso", guest:"Fabio Sasso", publication:"Latinxs Who Design", url:"https://podcasts.apple.com/us/podcast/best-investment-is-in-yourself-fabio-sasso/id1554011225?i=1000522086881&uo=4", verification:"primary"},
{id:"lwd-helena-jaramillo", type:"Podcast", year:2021, date:"2021-05-11", displayDate:"May 11, 2021", title:"I believe we can make good technology - Helena Jaramillo", guest:"Helena Jaramillo", publication:"Latinxs Who Design", url:"https://podcasts.apple.com/us/podcast/i-believe-we-can-make-good-technology-helena-jaramillo/id1554011225?i=1000521245363&uo=4", verification:"primary"},
{id:"lwd-ted-boda", type:"Podcast", year:2021, date:"2021-05-04", displayDate:"May 4, 2021", title:"Don't confuse visibility with success - Ted Boda", guest:"Ted Boda", publication:"Latinxs Who Design", url:"https://podcasts.apple.com/us/podcast/dont-confuse-visibility-with-success-ted-boda/id1554011225?i=1000519962122&uo=4", verification:"primary"},
{id:"lwd-andrea-pacheco", type:"Podcast", year:2021, date:"2021-04-27", displayDate:"Apr 27, 2021", title:"Be intentional - Andrea Pacheco", guest:"Andrea Pacheco", publication:"Latinxs Who Design", url:"https://podcasts.apple.com/us/podcast/be-intentional-andrea-pacheco/id1554011225?i=1000518757903&uo=4", verification:"primary"},
{id:"lwd-esteban-garc-a", type:"Podcast", year:2021, date:"2021-04-20", displayDate:"Apr 20, 2021", title:"Bold move that paid off - Esteban García", guest:"Esteban García", publication:"Latinxs Who Design", url:"https://podcasts.apple.com/us/podcast/bold-move-that-paid-off-esteban-garc%C3%ADa/id1554011225?i=1000517833277&uo=4", verification:"primary"},
{id:"lwd-jordi-tambillo", type:"Podcast", year:2021, date:"2021-04-13", displayDate:"Apr 13, 2021", title:"We want to belong - Jordi Tambillo", guest:"Jordi Tambillo", publication:"Latinxs Who Design", url:"https://podcasts.apple.com/us/podcast/we-want-to-belong-jordi-tambillo/id1554011225?i=1000516885901&uo=4", verification:"primary"},
{id:"lwd-pedro-marques", type:"Podcast", year:2021, date:"2021-04-06", displayDate:"Apr 6, 2021", title:"You are good enough - Pedro Marques", guest:"Pedro Marques", publication:"Latinxs Who Design", url:"https://podcasts.apple.com/us/podcast/you-are-good-enough-pedro-marques/id1554011225?i=1000515908995&uo=4", verification:"primary"},
{id:"lwd-marina-verdu", type:"Podcast", year:2021, date:"2021-03-29", displayDate:"Mar 29, 2021", title:"A mix of many things - Marina Verdu", guest:"Marina Verdu", publication:"Latinxs Who Design", url:"https://podcasts.apple.com/us/podcast/a-mix-of-many-things-marina-verdu/id1554011225?i=1000514945326&uo=4", verification:"primary"},
{id:"lwd-diego-rojas", type:"Podcast", year:2021, date:"2021-03-23", displayDate:"Mar 23, 2021", title:"Barriers in my head - Diego Rojas", guest:"Diego Rojas", publication:"Latinxs Who Design", url:"https://podcasts.apple.com/us/podcast/barriers-in-my-head-diego-rojas/id1554011225?i=1000514019528&uo=4", verification:"primary"},
{id:"lwd-desir-e-dezzie-garc-a", type:"Podcast", year:2021, date:"2021-03-16", displayDate:"Mar 16, 2021", title:"The web is a place of awe and wonder - Desirée (Dezzie) García", guest:"Desirée (Dezzie) García", publication:"Latinxs Who Design", url:"https://podcasts.apple.com/us/podcast/the-web-is-a-place-of-awe-and-wonder-desir%C3%A9e-dezzie-garc%C3%ADa/id1554011225?i=1000513149659&uo=4", verification:"primary"},
{id:"lwd-leandro-lima", type:"Podcast", year:2021, date:"2021-03-08", displayDate:"Mar 8, 2021", title:"Progressively less wrong - Leandro Lima", guest:"Leandro Lima", publication:"Latinxs Who Design", url:"https://podcasts.apple.com/us/podcast/progressively-less-wrong-leandro-lima/id1554011225?i=1000512005481&uo=4", verification:"primary"},
{id:"lwd-koji-pereira", type:"Podcast", year:2021, date:"2021-03-02", displayDate:"Mar 2, 2021", title:"Comes back to confidence - Koji Pereira", guest:"Koji Pereira", publication:"Latinxs Who Design", url:"https://podcasts.apple.com/us/podcast/comes-back-to-confidence-koji-pereira/id1554011225?i=1000511195825&uo=4", verification:"primary"},
{id:"lwd-tassia-pellegrini", type:"Podcast", year:2021, date:"2021-02-23", displayDate:"Feb 23, 2021", title:"Going full circle - Tassia Pellegrini", guest:"Tassia Pellegrini", publication:"Latinxs Who Design", url:"https://podcasts.apple.com/us/podcast/going-full-circle-tassia-pellegrini/id1554011225?i=1000510264545&uo=4", verification:"primary"},
{id:"lwd-trailer", type:"Podcast", year:2021, date:"2021-02-17", displayDate:"Feb 17, 2021", title:"Latinxs Who Design (Trailer)", publication:"Latinxs Who Design", url:"https://podcasts.apple.com/us/podcast/latinxs-who-design-trailer/id1554011225?i=1000509466537&uo=4", verification:"primary"},
{id:"v-channel", type:"Video", year:2023, date:"2023", title:"@multimichel on YouTube", sub:"Videos on design, careers, and working smarter — plus video episodes of the podcast.", url:"https://www.youtube.com/@multimichel", kind:"YouTube", publicArchive:false, verification:"primary"},
{id:"v-fieldnotes-1", type:"Video", year:2025, date:"2025", title:"Field Notes — Design systems for your whole organization", series:"Field Notes from Figma", role:["writer","presenter","producer/editor"], sub:"How growing teams use Figma's Org plan to scale consistency with shared libraries and org-wide defaults.", url:"https://www.figma.com/field-notes/design-systems-for-your-whole-organization/", kind:"Figma", note:"exact publish date not shown on source page", verification:"primary"},
{id:"v-fieldnotes-2", type:"Video", year:2025, date:"2025", title:"Field Notes — Building up the organization on Figma Admin", series:"Field Notes from Figma", role:["writer","presenter","producer/editor"], sub:"How design leaders use Figma Org's centralized admin to manage access and stay audit-ready.", url:"https://www.figma.com/field-notes/building-up-the-organization-on-figma-admin/", kind:"Figma", note:"exact publish date not shown on source page", verification:"primary"},
{id:"v-fieldnotes-3", type:"Video", year:2025, date:"2025", title:"Field Notes — Scaling up your design system", series:"Field Notes from Figma", role:["writer","presenter","producer/editor"], sub:"How teams use branching, variable modes and library analytics to ship changes with confidence.", url:"https://www.figma.com/field-notes/scaling-up-your-design-system/", kind:"Figma", note:"exact publish date not shown on source page", verification:"primary"},
{id:"a-lovers", type:"Interview", year:2018, date:"2018", title:"Lovers Magazine — interview", url:"https://www.loversmagazine.com/interviews/michel-ferreira", kind:"Magazine", lang:"en", verification:"primary"},
{id:"a-bear", type:"Interview", year:2021, date:"2021", title:"Bear Academy — podcast interview", url:"https://www.youtube.com/watch?v=jblSD6JBbKc", kind:"Podcast", lang:"en", verification:"primary"},
{id:"a-desenhando", type:"Interview", year:2021, date:"2021", title:"Desenhando Produtos — podcast interview", url:"https://open.spotify.com/episode/287IbodADE0CaVjbpAnqRH", kind:"Podcast", lang:"pt-BR", verification:"primary"},
{id:"a-cultne", type:"Interview", year:2021, date:"2021", title:"Cultne — television interview", url:"https://www.youtube.com/watch?v=0I-Esj2a-bs", kind:"Television", lang:"pt-BR", verification:"primary"},
{id:"a-stbcast", type:"Interview", year:2021, date:"2021", title:"STBcast — podcast interview", url:"https://www.youtube.com/watch?v=jvt18XJRHOg", kind:"Podcast", lang:"pt-BR", verification:"primary"},
{id:"a-friendly-futurist", type:"Interview", year:2026, date:"2026-06-10", displayDate:"Jun 10, 2026", title:"The Friendly Futurist — How Does Design Flow Through Everything?", sub:"With Alex and Michel from Figma, on AI, design and human-centred thinking.", url:"https://podcasts.apple.com/tw/podcast/how-does-design-flow-through-everything-interview-with/id1601365640?i=1000772087307", kind:"Podcast", lang:"en", verification:"secondary"},
{id:"x-copy-paste", type:"Experiment", year:2024, date:"2024", title:"The Copy Paste Club", sub:"An album made with AI, for fun.", url:"https://open.spotify.com/artist/4h20EEaSsJha8OKMiTfINg", verification:"user"},
{id:"x-mentor", type:"Artifact", year:2021, date:"2021", title:"Mentorship — Dribbble's Scaling Design Systems course & ADPList", url:"https://adplist.org/mentors/michel-ferreira", publicArchive:false, verification:"primary"},
{id:"x-github-io", type:"Artifact", year:2022, date:"2022", title:"multimichel.github.io — a previous home on the internet", url:"https://multimichel.github.io/", publicArchive:false, verification:"primary"}
]};

// ---------- link semantics ----------
// One arrow language across the whole site:
//   →  internal navigation (another page or section of this site)
//   ↗  external destination (leaves the site)
// Every list template routes through these so an arrow is decided once, in one
// place, and never appended twice to a string that already carries one.
window.MM.isExternal = function(href){
  return /^(https?:)?\/\//i.test(href || "") || /^mailto:/i.test(href || "");
};
window.MM.arrow = function(href){
  if (!href) return "";
  return window.MM.isExternal(href) ? " ↗" : " →";
};
// The action arrow for an editorial row. It is rendered as a SIBLING of the
// title, not appended to the title text, so it holds one quiet position at the
// row's right edge and a wrapping title never has to flow around it.
// Compact navigation labels ("ALL WRITING →") keep their arrow inline in the
// markup — they are labels, not rows.
window.MM.actionMark = function(href){
  if (!href) return "";
  return '<span class="go" aria-hidden="true">'
       + (window.MM.isExternal(href) ? '↗' : '→') + '</span>';
};
// External links leave the site: new tab + full rel. Internal links stay put.
window.MM.linkAttrs = function(href){
  return window.MM.isExternal(href) ? ' target="_blank" rel="noopener noreferrer"' : '';
};
